project: MLDeploy
workflows:
  - name: training
    steps:
      - name: a
        module: ./ml/training/a.py
        function: step_fn
        dependencies: null
        return:
          - x1
          - x2
      - name: b
        module: ./ml/training/b.py
        function: step_fn
        dependencies: null
        return: null
      - name: c
        module: ./ml/training/c.py
        function: step_fn
        dependencies:
          - type: param
            name: x1
            source:
              step: a
              param: x1
          - type: param
            name: x2
            source:
              step: a
              param: x2
          - type: order
            name: start
            source:
              step:
                - b
        return:
          - x4
          - x5
      - name: d
        module: ./ml/training/d.py
        function: step_fn
        dependencies:
          - type: param
            name: x5
            source:
              step: c
              param: x4
        return:
          - x6
    schedule: "*/1 * * * *"
  - name: inference
    steps:
      - name: a
        module: ./ml/inference/a.py
        function: step_fn
        dependencies: null
        return:
          - x1
          - x2
      - name: b
        module: ./ml/inference/b.py
        function: step_fn
        dependencies: null
        return: null
      - name: c
        module: ./ml/inference/c.py
        function: step_fn
        dependencies:
          - type: param
            name: x1
            source:
              step: a
              param: x1
          - type: param
            name: x2
            source:
              step: a
              param: x2
          - type: order
            name: start
            source:
              step:
                - b
        return:
          - x4
          - x5
      - name: d
        module: ./ml/inference/d.py
        function: step_fn
        dependencies:
          - type: param
            name: x5
            source:
              step: c
              param: x4
        return:
          - x6
    schedule: "*/1 * * * *"
